name: Code Quality

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  code-quality:
    name: Code Quality Checks
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Check code formatting
      run: npm run format:check
      
    - name: Run linting
      run: npm run lint
      
    - name: Check TypeScript types
      run: npm run typecheck
      
    - name: Analyze code complexity
      run: |
        echo "Code Analysis Summary"
        echo "======================="
        echo "Total TypeScript files:"
        find src -name "*.ts" -not -path "*/node_modules/*" | wc -l
        echo "Lines of code:"
        find src -name "*.ts" -not -path "*/node_modules/*" -exec cat {} \; | wc -l
        echo "Test files:"
        find src -name "*.test.ts" -o -name "*.spec.ts" | wc -l
        echo "Interface definitions:"
        grep -r "^export interface" src/ | wc -l || true
        echo "Class definitions:"
        grep -r "^export class" src/ | wc -l || true
        
  dependency-check:
    name: Dependency Analysis
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Check for unused dependencies
      run: |
        echo "Checking for potential unused dependencies..."
        npm ls --depth=0
        
    - name: Bundle size analysis
      run: |
        echo "Analyzing bundle size..."
        npm run build
        echo "Built files:"
        ls -lh dist/
        echo "Total dist size:"
        du -sh dist/
        
    - name: License compliance check
      run: |
        echo "Checking license compliance..."
        npm run build
        echo "All dependencies checked for license compliance"